### ISSUE TITLE
Chromium download

### ISSUE THREAD

**Issue by cilerler** [qjebbs/vscode-markdown-extended#15]
Whenever I receive an update it asks me if I want to download Chromium.  
Is there a way to set in settings so it can check that before it is downloading?  
Even further where is the location it keeps download Chromium?

Thanks in advance

**Comment by qjebbs** [comment]
PS: the Chromium downloaded to the extension dir, which is removed on you update. That's why it keeps asking. That's  the [puppeteer behavior](https://github.com/GoogleChrome/puppeteer/blob/v1.4.0/docs/api.md#browserfetcherdownloadrevision-progresscallback), and I cannot change it. The best solution is `markdownExtended.puppeteerExecutable`

**Comment by cilerler** [comment]
Well if it is the same directory then that is OK since it deletes it.  I was looking for that, I appreciate your fast response and thank you VERY MUCH for the great extension you provide!

**Comment by cilerler** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/469d4aea-0aaa-4b89-919e-0fd853b6f0f0-1d989a62-ae8a-48a8-b04f-0f575358153a-v1.png?transparent=1&palette=1&width=246)

**Comment by qjebbs** [comment]
My pleasure!
