### ISSUE TITLE
Duplicate html elements in export

### ISSUE THREAD

**Issue by AceTheWiz** [qjebbs/vscode-markdown-extended#28]
There are duplicates of the same element and attribute when exporting to html.

This is my markdown.
```
# HeaderPlain
# HeaderwithAttr {.classid #idid}
ABBR
*[ABBR]: This is an abbreviation.
```
This is the html output
```
<a for="toc-anchor" id="headerplain"></a>
<a for="toc-anchor" id="headerplain"></a>
<a for="toc-anchor" id="headerplain"></a>
<a for="toc-anchor" id="headerplain"></a>
<h1 id="headerplain-4" data-line="0" class="code-line code-line code-line code-line" id="headerplain-5" id="headerplain-6" id="headerplain-7">HeaderPlain</h1>

<a for="toc-anchor" id="headerwithattr-%7B.classid-%23idid%7D"></a>
<a for="toc-anchor" id="headerwithattr-%7B.classid-%23idid%7D"></a>
<a for="toc-anchor" id="headerwithattr-%7B.classid-%23idid%7D"></a>
<a for="toc-anchor" id="headerwithattr-%7B.classid-%23idid%7D"></a>
<h1 class="classid code-line code-line code-line code-line" id="idid" id="headerwithattr-4" data-line="2" id="headerwithattr-5" id="headerwithattr-6" id="headerwithattr-7">HeaderwithAttr</h1>

<p data-line="4" class="code-line code-line code-line code-line">
	<abbr title="This is an abbreviation.">
		<abbr title="This is an abbreviation.">
			<abbr title="This is an abbreviation.">
				<abbr title="This is an abbreviation.">ABBR</abbr>
			</abbr>
		</abbr>
	</abbr>
</p>
```
### Issues
1. The element ```<a for="toc-anchor" id="headerplain"></a>``` is repeated 4 times.
2. The class attribute has multiple of the same class. "code-line" ```class="code-line code-line code-line code-line"```
3. For the HeaderwithAttr, the attributes {.classid #idid} become part of the H1 element Id ```id="headerwithattr-%7B.classid-%23idid%7D"```
4. There are multiple H1 element Id's ```id="headerwithattr-4"``` ```id="headerwithattr-5"```, ```id="headerwithattr-6"```, ```id="headerwithattr-7"```
5. The ABBR function adds the same element 4 times (nested).

These are not expected behaviors. Could you help please ?

### What I tried
Disabled all other extensions. Same issue.
Export to file. Same issue.

### Environment
- Windows 7
- VSCode v1.29 (user setup).
- Markdown Extended v1.0.3

**Comment by qjebbs** [comment]
I'll investigate

**Comment by qjebbs** [comment]
It may be a bug of VSCode, below is a test result under this circumstances:

1. Disabled all contributed plugins to MarkdownIt. (Not my whole extension, but plugins of the extension)
1. In production environment, no in extension debugging environment

Markdown Input:

```md
## abc
```

HTML output

```html
<h2 id="abc" data-line="NaN" class="code-line code-line code-line" id="abc-1" id="abc-2">abc</h2>
```

We can see the `<h2>` got 3 `id` attributes (4 in your example). 

Seems that every plugin of markdownIt was called many times, that's why you got 4 `id` attributes, 4 `toc-anchor`, and I got 3 here.

The reason why I emphasize "In production environment" is:

1. In extension debugging environment, the issue is gone, I got 1 `id` and 1 `<h2>`
1. Months ago, I observed the converse behavior, that, debugging environment call plugin many times while production does not. And I don't take it as a serious bug, since it's only in debugging environment.

This bug could be hard to discover, it doesn't change the preview rendering, but when user use export feature, my extension exposes it.
