### ISSUE TITLE
LaTeX gets a little wonky on PDF Export

### ISSUE THREAD

**Issue by oliver-daniel** [qjebbs/vscode-markdown-extended#48]
Hello,
Loving the extension -- super useful.

When I use LaTex display math, the preview looks as normal:
![Screen Shot 2019-04-26 at 8 11 16 PM](https://user-images.githubusercontent.com/17235417/56842043-ade29400-685f-11e9-9fbd-55aa5607204e.png)

Unfortunately, when I export to PDF using the extension, the same math looks like so:
![Screen Shot 2019-04-26 at 8 11 36 PM](https://user-images.githubusercontent.com/17235417/56842052-c05ccd80-685f-11e9-9aa6-da80f61984e7.png)

Any clues?
Cheers!

**Comment by oliver-daniel** [comment]
(To be clear, my specific issue is with the bounds on the two integrals.)

**Comment by qjebbs** [comment]
Do you preview with native markdown previewer, other than other plugins like markdown-all-in-one?

**Comment by oliver-daniel** [comment]
> Do you preview with native markdown previewer, other than other plugins like markdown-all-in-one?

The only two Markdown extensions I am using are markdown-all-in-one and this.

**Comment by qjebbs** [comment]
Sorry, having busy days...I still cannot reproduce the problem, maybe it's about style conflict, I did find some inconsistencies in the past, like this two:

preview: <img width="398" alt="image" src="https://user-images.githubusercontent.com/16953333/58746491-61f3c200-8491-11e9-9c02-b8e7033e69b0.png">

export: <img width="200" alt="image" src="https://user-images.githubusercontent.com/16953333/58746493-67510c80-8491-11e9-87f1-e4c2aa321bb9.png">

**Comment by Aritmoss** [comment]
I don't know if this could be caused by the same inconsistencies in the rendering but in my case, the \mathcal and \mathbb fonts do not show correctly when exporting the file into any format. Only using markdown-all-in-one and markdown-extended here is how the preview looks and how the pdf outputs:
![preview](https://user-images.githubusercontent.com/52433836/60476132-acc44d80-9c7a-11e9-9190-bc283c7f208a.PNG)
![pdf](https://user-images.githubusercontent.com/52433836/60476134-af26a780-9c7a-11e9-9d41-79d75db16fac.PNG)
I've been trying to fix this for days now and just hope there is a simple solution!

**Comment by qjebbs** [comment]
should've fix the issue of @Aritmoss, but not sure for @oliver-daniel, please re-open this issue if not.
