### ISSUE TITLE
opt-cursor to navigate text not working in OS X

### ISSUE THREAD

**Issue by DaveEveritt** [qjebbs/vscode-markdown-extended#57]
When this extension is enabled, option-left-right cursor fails to move the cursor to the next word. Option-up-down-cursor is fine.

- OS X 10.14.6
- VSCode Version: 1.38.0

Same applies to the equivalent shortcuts in Windows.

**Comment by cilerler** [comment]
Same applies to Windows too 🚨

**Comment by qjebbs** [comment]
@cilerler I only see `Expand Selection` with the same shortcut, and they don't seem to be conflict. If your `mark word` feature is contributed by another extension, change either this or that shortcut, to make them work both.

![image](https://user-images.githubusercontent.com/16953333/66622781-9fc0de00-ec1b-11e9-933e-69c95a04c40a.png)
![image](https://user-images.githubusercontent.com/16953333/66622870-ef9fa500-ec1b-11e9-987c-92d412e289cf.png)

**Comment by cilerler** [comment]
I have `cursorWordAccessibilitySelect` but I don't think they are related
![image](https://user-images.githubusercontent.com/385958/66624414-00213280-ebbe-11e9-9d0a-01219482ef13.png)

**Comment by qjebbs** [comment]
The built-in `ctrl+shift+right` command is only the `Expand Selection`, other commands are contributed by extensions, now that they use same shortcuts, change either one of them.

I mean, I cannot promise that my shortcuts don't conflict with other extensions, since there are so many of them.

**Comment by cilerler** [comment]
`Expand Selection` is <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>Arrow</kbd> on my computer.  _(I never touched it, so I assume it is default)_

Again, everything was just fine until your last update. And upon your suggestion I changed `Markdown:MoveColumnLeft` and `Markdown:MoveColumnRight` to something other than <kbd>CTRL</kbd>+<kbd>Shift</kbd>+<kbd><-</kbd> and <kbd>CTRL</kbd>+<kbd>Shift</kbd>+<kbd>-></kbd>and it started to work.

My 2 cents say you should change those bindings. Even for me, it was a frustrating couple of days since it took me a while to realize that it happens only for markdown files. And finally, I couldn't stand anymore and had to dig.  Not an average user can identify it, and even further, they may think it is a virus. You may want to pick some other combination for moving columns Left/Right should be a different combination.  I chose the same mix with <kbd>Tab</kbd> 😂 

Regardless, thanks for the quick reply. 

> _side note: by the way, you should definitely apply for this https://github.com/sponsors_

**Comment by JoBrad** [comment]
The [Shift+]Ctrl+Left/RightArrow default shortcuts should definitely not be overridden, since they are almost universally used in text editors for text selection and navigation. Perhaps fewer people use the [Shift+]Alt+Left/RightArrow shortcuts, and would be less affected if you overrode those, instead?

**Comment by cilerler** [comment]
@JoBrad using <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd><-</kbd> or <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>-></kbd> would be an issue too. I strongly suggest not to overwrite any default shortcuts for no reason. Try to use `Expand Selection` double click you will see it will mark entire row, and so many people uses that too.

Also @qjebbs you may want to remove `in OS X` from the title since it affects Windows too.

**Comment by qjebbs** [comment]
Thanks for all informations from your discussions, maybe the better way is to remove the default shortcut, and let user to define it.

**Comment by JoBrad** [comment]
Appreciate the positive response, @qjebbs!
