### ISSUE TITLE
italics in preview displayed as underscores

### ISSUE THREAD

**Issue by gmccullo** [qjebbs/vscode-markdown-extended#72]
With this extension enabled, \_this text_ would be displayed in the preview underscored. With the extension off, \_this text_ is displayed as italic, which is correct.

**Comment by Trillinon** [comment]
I believe this is because the extension has added `markdown-it-underline` as a supported extension. I disagree with this choice, as it isn't an extension of the Markdown syntax but an override. I use the underscore for italics, and now my documents no longer render correctly.

I think the underline extension should be removed, and made into a separate markdown plugin extension. At the very least, as the list of extensions grows, they should be configurable.

**Comment by qjebbs** [comment]
Please use `*italic*` for *italic*

**Comment by gmccullo** [comment]
Here's the [spec](https://daringfireball.net/projects/markdown/syntax#em):

> Markdown treats asterisks (`*`) and underscores (`_`) as indicators of emphasis. Text wrapped with one `*` or `_` will be wrapped with an HTML `<em>` tag; double `*`’s or `_`’s will be wrapped with an HTML `<strong>` tag.

\_italic_ is italic. The extension should conform to the specification.
